# Generated by Django 4.2.7 on 2024-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
