# Generated by Django 4.2.7 on 2024-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_product_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producr_description',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
