# Generated by Django 4.2.7 on 2024-03-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_producr_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producr_description',
            new_name='product_description',
        ),
    ]
