# Generated by Django 4.2.7 on 2024-03-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_vendorprofile_bio_vendorprofile_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
